version: 2

formats: ["pdf", "epub"]

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    build:
      pdf:
        - sphinx-build -b rinoh docs $READTHEDOCS_OUTPUT/pdf/
