version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp index.html $READTHEDOCS_OUTPUT/html/index.html
