version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  commands:
    - cargo --version
    - cargo install mdbook
    - asdf reshim rust
    - mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html
