version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: latest
  jobs:
    pre_create_environment:
      - asdf update
      - asdf plugin update --all
      - asdf install python miniforge3-24.11.2-1
      - asdf global python miniforge3-24.11.2-1 || true
    post_build:
      - cat /tmp/python-build.*.log
      - ls /tmp/python-build.*

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yaml
